name: Deploy
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  ITCH_USERNAME: delzhand
  ITCH_GAME_ID: isocon

jobs:
  deploy:
    name: Upload to Itch.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - windows
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Get the latest release
        id: latest_release
        run: echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Fetch the latest release asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'delzhand/isocon'
          version: ${{ env.tag }}
          file: 'isocon_win.zip'
          target: 'build/isocon_win.zip'
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
          gameData: ./build/isocon_win.zip
          itchUsername: ${{ env.ITCH_USERNAME }}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ env.tag }}
