name: Deploy
on:
  release:
    types: [ published ]
env:
  ITCH_USERNAME: delzhand
  ITCH_GAME_ID: isocon
jobs:
  deploy:
    name: Upload to Itch.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - windows
    runs-on: ubuntu-latest
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'delzhand/isocon'
          version: 'tags/v0.6.8'
          file: 'isocon_win.zip'
          target: 'build/isocon_win.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_CREDENTIALS}}
          gameData: ./build/isocon_win.zip
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
